### ISSUE TITLE
Problema Gravíssimo

### ISSUE THREAD

**Issue by pedrosilvajava** [MarcosVMoreira/iFood-Clone#20]
Após eu fazer breve análise vi que o Back-End não possui testes implementados. Mesmo se tratando de projeto de faculdade o esperado é que tudo seja testado.

[Segue um bom artigo sobre o assunto. ](https://martinfowler.com/articles/practical-test-pyramid.html
)

Espero que consigam se formar, mas caso não tenha teste, seria legal para não gerar mais este débito social.

**Comment by MarcosVMoreira** [comment]
Se você fizer uma melhor análise, perceberá que o microsserviço de customer possui sim testes unitários. Todavia decidi por deixar de lado testes unitários momentaneamente, assim como praticar o TDD, por focar em outras atividades para acelerar o desenvolvimento. 

Estamos com prazo curto e decidi manter a qualidade em outros aspectos, o que faz parte de um bom gerenciamento de projeto.

No futuro pretendo voltar e testar, mas de momento o objetivo é deployar num K8 e escalar.

**Comment by pedrosilvajava** [comment]
Peço desculpas se você se sentiu ofendido de alguma forma, mas teste é importante e o github é para isso, melhoria continua, discussões sadias e muito códigooooooooo!

Você só perde muito tempo arrumando código que já estava funcionando e sua falta de análise de impacto quebra outras partes, vai gastar muito mais tempo. Além de não ser um código confiável.

**O IFood é 100% testado e toda entrega com urgência máxima é testada com cobertura de 100%.** 

Converse com alguém mais Sênior sobre este tópico ou com o professor que está orientando o projeto.
Leve esta discussão para o seu gerente ler e veja ele concorda com a não implementação de teste unitário, leve junto seu líder técnico. 

Mais uma vez peço desculpas por algo.

**Comment by MarcosVMoreira** [comment]
No dia a dia do mercado, não almejamos 100% de covarage pois isso implica em testar códigos desnecessários. Testamos apenas aquilo que assegura regras de negócio das aplicações.

Assim como você pode ver no próprio artigo que me enviou, o autor não aconselha 100% de covarage pelo mesmo motivo que não sigo nesse projeto.

Abraços! 

![IMG_20210113_071118](https://user-images.githubusercontent.com/35854051/104438309-9f299c80-556e-11eb-9568-01f747af4405.jpg)
